"""add signature field to user table

Revision ID: 2b5db0d9b2db
Revises: d9ec01d9975b
Create Date: 2025-01-12 12:24:15.153317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b5db0d9b2db'
down_revision: Union[str, None] = 'd9ec01d9975b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_inputs', sa.Column('signature', sa.String(length=32), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_inputs', 'signature')
    # ### end Alembic commands ###
