"""Initial migration

Revision ID: 8283fa5a5e51
Revises: 
Create Date: 2024-05-29 16:07:18.179034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8283fa5a5e51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'copy_email', 'email', ['email_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'copy_email', type_='foreignkey')
    op.drop_column('account', 'email')
    # ### end Alembic commands ###
