"""Initial migration

Revision ID: d9ec01d9975b
Revises: ae028744a4f9
Create Date: 2025-01-11 21:44:57.038899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9ec01d9975b'
down_revision: Union[str, None] = 'ae028744a4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=28), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名，可用于登录'),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('NORMAL', 'ADMIN', 'SUPER', name='usertype'), nullable=False),
    sa.Column('login_type', sa.Enum('EMAIL', 'USERNAME', 'PHONE', name='logintype'), nullable=False, comment='登录方式'),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('last_time', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('emailCode', sa.Enum('UNBOUND', 'BOUND', 'ERROR', name='emailstatus'), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False, comment='用户头像'),
    sa.Column('is_registered', sa.Integer(), nullable=False, comment='注册状态：0=未注册完成，1=注册成功'),
    sa.Column('status', sa.Enum('NORMAL', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('sex', sa.Enum('UNKNOWN', 'MALE', 'FEMALE', name='usersex'), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_inputs_email_login_type', 'user_inputs', ['email', 'login_type'], unique=False)
    op.create_index('ix_user_inputs_username_login_type', 'user_inputs', ['username', 'login_type'], unique=False)
    op.create_table('user_login_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('login_date', sa.Date(), nullable=False, comment='登录日期'),
    sa.Column('login_time', sa.Integer(), nullable=False, comment='登录时间戳'),
    sa.Column('continuous_days', sa.Integer(), nullable=True, comment='连续登录天数'),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('last_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_logout_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logout_time', sa.BigInteger(), nullable=False, comment='登出时间戳'),
    sa.Column('logout_date', sa.Date(), nullable=False, comment='登出日期'),
    sa.ForeignKeyConstraint(['user_id'], ['user_inputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_logout_date', 'user_logout_records', ['user_id', 'logout_date'], unique=False)
    op.drop_table('account')
    op.drop_table('copy_email')
    op.drop_table('email')
    op.drop_table('signature')
    op.drop_table('languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('text', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('href', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('signature',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], name='signature_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('email',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=21), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=420), nullable=False),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('copy_email',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=21), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=420), nullable=False),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], name='copy_email_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('emailStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index('idx_user_logout_date', table_name='user_logout_records')
    op.drop_table('user_logout_records')
    op.drop_table('user_login_record')
    op.drop_index('ix_user_inputs_username_login_type', table_name='user_inputs')
    op.drop_index('ix_user_inputs_email_login_type', table_name='user_inputs')
    op.drop_table('user_inputs')
    # ### end Alembic commands ###
