"""Initial migration

Revision ID: ff58436c9954
Revises: 2b5db0d9b2db
Create Date: 2025-01-12 12:27:48.547499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff58436c9954'
down_revision: Union[str, None] = '2b5db0d9b2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_logout_date', table_name='user_logout_records')
    op.drop_table('user_logout_records')
    op.drop_table('copy_email')
    op.drop_table('signature')
    op.drop_table('account')
    op.drop_table('email')
    op.drop_table('languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('text', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('href', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('email',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=21), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=420), nullable=False),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('emailStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('signature',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], name='signature_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('copy_email',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=21), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=420), nullable=False),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], name='copy_email_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_logout_records',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('logout_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='登出时间戳'),
    sa.Column('logout_date', sa.DATE(), nullable=False, comment='登出日期'),
    sa.ForeignKeyConstraint(['user_id'], ['user_inputs.id'], name='user_logout_records_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_logout_date', 'user_logout_records', ['user_id', 'logout_date'], unique=False)
    # ### end Alembic commands ###
